### ISSUE TITLE
Not A issue

### ISSUE THREAD

**Issue by rameshvoltella** [simonpercic/WaterfallCache#1]
first happy to see a awesome cache library using rx java :), when i use this cache i noticed you are adding a strict mode in application class, what is the use of adding strict mode

**Comment by simonpercic** [comment]
Using [StrictMode](http://developer.android.com/reference/android/os/StrictMode.html) we can detect any accidental network or disk access that happens on the app's main thread.

I find that to be a good practice, so we can catch potential issues early on during development. However, it should only be set in the development build.

In the included sample app I have turned on StrictMode in the main application class: [App.java](https://github.com/simonpercic/WaterfallCache/blob/master/waterfallcache-sample/src/main/java/com/github/simonpercic/waterfallcachesample/App.java), yet it does not have any impact on the library's behavior. It's just something I usually add and have also left it in in the sample app.

I'm glad that you like the library. :smiley:

**Comment by rameshvoltella** [comment]
thanks man for the clarification ,again a useful cache library well done :+1:
